### ISSUE TITLE
Recall hotkey generates Error 429

### ISSUE THREAD

**Issue by gmn42** [netniV/tashcan-bob#2]
In 2023-10-07 development rev, the 'R' key generates an on-screen Error 429 message.  

![image](https://github.com/netniV/tashcan-bob/assets/78309818/d86c7664-732b-4d2c-a5b9-742d243dfe73)
If the target is in the same system, the ship returns to base normally, but leaves an extra 'trail' behind if retargetted before reaching base.  

![image](https://github.com/netniV/tashcan-bob/assets/78309818/b700e995-d4d0-404a-95e3-b388279b5663)

If the target ship is in a different system, the Error 429 appears and there is no visual change on-screen until the warp timer expires, at which point the ship warps out normally.  The warp timer itself (on HUD icon) does not appear.

This is new behavior relative to the currently release community patch v0.5.3.

**Comment by netniV** [comment]
I've put some extra checks in for the .2 test.  Not sure it is resolved yet fully.

**Comment by netniV** [comment]
5.3.3.4 should now hopefully have corrected this.
